# In the following requests the variable baseUrl is used.
# Its value is set here.
@baseUrl = http://localhost:4004



### ------------------------------------------------------------------------
# Create a new author with the date of death before the date of birth.
POST {{baseUrl}}/admin/Authors
Content-Type: application/json

{
  "name": "Stephen Hawking",
  "dateOfBirth": "1942-01-08",
  "dateOfDeath": "2018-03-14", 
  "ID":  "130"
}